### ISSUE TITLE
about efficient_integer_inference convolution computation

### ISSUE THREAD

**Issue by ai-libo** [soon-yau/QNN#2]
Hello, I'm doing tflite aware training in FPGA implementation , with reference to your code. 07 _efficient_integer_inference ipynb, but you does not  show convolution computation in the code, so I refer wrote it but the output compared with tflite inference output does not match, so, would you please contribute to this part of the calculation code? Or you can give me some materials for reference Thank you very much

**Comment by soon-yau** [comment]
The convolution is standard and it is quite straight forward to write one yourself, I'll try to find some this week to add that to the tutorial. It is normally the minor details e.g. padding, quantization range, rounding etc that cause the data to be not 100% bit exact.

Did you say you were trying to do the training on FGPA, or was it only inference? The best way to debug this problem is to construct a single conv layer in TF, then convert it to TFLite model to generate test vectors and use that to check your FPGA output.
